### ISSUE TITLE
Generating XML - BT-262-Procedure is not included in the correct parent

### ISSUE THREAD

**Issue by LukacikPavel** [OP-TED/eforms-notice-editor#11]
Hello,
current version is unable to generate XML of notices containing BT-262-Procedure (Main Classification Code).

Error message:
```
 Problem in visual node hierarchy, unexpected missing repeatable nodeId=ND-ProcedureMainClassification 
 Problem in visual node hierarchy, fieldId=BT-262-Procedure is not included in the correct parent. Expecting ND ProcedureMainClassification but found ND-Root
```

Could you take a look at it?
Thank you.

**Comment by rouschr** [comment]
For SDK related issues please report problems in the SDK project.
To clarify: the editor demo uses the SDK metadata, so if there is a problem with the forms related to hierarchy it is likely due to a problem in the SDK.
After looking into my local files I see that this problem has been fixed in the SDK 1.9 (not released yet).
SDK 1.9 will be a lot better for XML generation, especially because of the attribute fields.
